# Generated by Django 2.0.5 on 2020-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='submit_deadline',
            field=models.DateField(auto_now=True),
        ),
    ]
