# Generated by Django 2.0.5 on 2020-01-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(default='Leaderboard', max_length=150),
        ),
    ]
